- name: Installing stow
  ansible.builtin.package: 
    name: 
      - stow
      - tmux
  become: true
  tags:
    - install
    - dotfiles
    - stow
    - tmux

- name: Remove Zsh config
  become: true
  file:
    path:  "{{ lookup('env', 'HOME') }}/.zsh"
    state: absent
  tags:
    - zsh
    - dotfiles

- name: Remove bin config
  become: true
  file:
    path:  "{{ lookup('env', 'HOME') }}/.local/bin"
    state: absent
  tags:
    - bin
    - dotfiles

- name: Remove alias config
  become: true
  file:
    path:  "{{ lookup('env', 'HOME') }}/.config/aliasrc"
    state: absent
  tags:
    - alias
    - dotfiles


- name: Remove alias config
  become: true
  file:
    path:  "{{ lookup('env', 'HOME') }}/.config/nvim"
    state: absent
  tags:
    - neovim
    - dotfiles


- name: Remove tmux 1
  become: true
  file:
    path:  "{{ lookup('env', 'HOME') }}/.tmux-cht-command"
    state: absent
  tags:
    - tmux
    - dotfiles

- name: Remove tmux 2
  become: true
  file:
    path:  "{{ lookup('env', 'HOME') }}/.tmux-cht-languages"
    state: absent
  tags:
    - tmux
    - dotfiles

- name: Remove tmux 3
  become: true
  file:
    path:  "{{ lookup('env', 'HOME') }}/.tmux.conf"
    state: absent
  tags:
    - tmux
    - dotfiles

- name: Stow dotfiles
  shell: cd $HOME/.dev && stow alias && stow zsh && stow nvim && stow bin && stow tmux
  tags:
    - stow
    - dotfiles
