- name: Install Neovim install dependencies
  become: true
  ansible.builtin.package:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
      - ripgrep
      - fzf
  tags:
    - install
    - neovim

- name: Remove Neovim folder
  become: true
  file:
    path:  "{{ lookup('env', 'HOME') }}/neovim"
    state: absent
  tags:
    - install
    - neovim

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
  tags:
    - install
    - neovim

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - install
    - neovim

- name: Clone Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim.git'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1
  tags:
    - install
    - neovim

- name: Install Packer dependencies
  become: true
  shell: "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'silent PackerSync'"
  tags:
    - install
    - neovim
